### ISSUE TITLE
pip3 doesn't install the dependencies

### ISSUE THREAD

**Issue by jpantao** [jmg-duarte/scrape-the-box#3]
Installing:
```
$ pip3 install --editable .
Obtaining file:///home/jpantao/Documents/gcs/scrape-the-box
Installing collected packages: scrape-the-box
  Found existing installation: scrape-the-box 0.1.1
    Uninstalling scrape-the-box-0.1.1:
      Successfully uninstalled scrape-the-box-0.1.1
  Running setup.py develop for scrape-the-box
Successfully installed scrape-the-box
```

Running:
```
$ stb
Traceback (most recent call last):
  File "/home/jpantao/.local/bin/stb", line 11, in <module>
    load_entry_point('scrape-the-box', 'console_scripts', 'stb')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jpantao/Documents/gcs/scrape-the-box/stb/cli.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'
```

**Comment by jpantao** [comment]
`$ pip3 install --editable .
Obtaining file:///home/jpantao/Documents/gcs/scrape-the-box
Installing collected packages: scrape-the-box
  Found existing installation: scrape-the-box 0.1.1
    Uninstalling scrape-the-box-0.1.1:
      Successfully uninstalled scrape-the-box-0.1.1
  Running setup.py develop for scrape-the-box
Successfully installed scrape-the-box
`
`$ stb
Traceback (most recent call last):
  File "/home/jpantao/.local/bin/stb", line 11, in <module>
    load_entry_point('scrape-the-box', 'console_scripts', 'stb')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jpantao/Documents/gcs/scrape-the-box/stb/cli.py", line 1, in <module>
    import click
ModuleNotFoundError: No module named 'click'`

**Comment by jmg-duarte** [comment]
This should be fixed in https://github.com/jmg-duarte/scrape-the-box/commit/fc4b4ca16729ebf0c4541b8f0c2c773cbf796f13. In any case README has been updated and the new instructions should now work
